name       : python-blinker
version    : '1.5'
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/b/blinker/blinker-1.5.tar.gz : 923e5e2f69c155f2cc42dafbbd70e16e3fde24d2d4aa2ab72fbe386238892462
homepage   : https://github.com/pallets-eco/blinker
license    : MIT
component  : programming.python
summary    : Fast, simple object-to-object and broadcast signaling
description: |
    Blinker provides fast & simple object-to-object and broadcast signaling for Python objects.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
