name       : python-blinker
version    : 1.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/b/blinker/blinker-1.4.tar.gz : 471aee25f3992bd325afa3772f1063dbdbbca947a041b8b89466dc00d606f8b6
license    : MIT
component  : programming.python
summary    : Fast, simple object-to-object and broadcast signaling
description: |
    Blinker provides fast & simple object-to-object and broadcast signaling for Python objects.
builddeps  :
    - python-nose
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test nosetests
    %python3_test nosetests-%python3_version%
