name       : python-blinker
version    : 1.6.2
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/b/blinker/blinker-1.6.2.tar.gz : 4afd3de66ef3a9f8067559fb7a1cbe555c17dcbe15971b05d1b625c3e7abe213
homepage   : https://github.com/pallets-eco/blinker
license    : MIT
component  : programming.python
summary    : Fast, simple object-to-object and broadcast signaling
description: |
    Blinker provides fast & simple object-to-object and broadcast signaling for Python objects.
builddeps  :
    - python-build
    - python-installer
    - python-pytest-asyncio # check
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
